### ISSUE TITLE
Yarn is not installed

### ISSUE THREAD

**Issue by cipolleschi** [CircleCI-Public/macOS-M1-Preview-Documentation#7]
When trying M1 machines on [React Native](https://github.com/facebook/react-native), it looks like yarn is not installed.

You can have a look at the PR [here](https://github.com/facebook/react-native/pull/36375/files)
[Here](https://app.circleci.com/pipelines/github/facebook/react-native?branch=cipolleschi%2Ftest_m1_machines), you can see the pipelines.

## Workaroud
I manage to work around this issue adding a custom step before the :

```
     - run:
          name: "Install Yarn if needed"
          command: |
            if [[ -z "$(command -v yarn)" ]]; then
              npm install --global yarn
            else
              echo "Yarn installed; Skipping"
            fi
```

**Comment by alexazl** [comment]
@cipolleschi As with the other issue you opened, please open a support ticket to investigate this issue further. Many thanks!
