### ISSUE TITLE
Ruby is not working

### ISSUE THREAD

**Issue by cipolleschi** [CircleCI-Public/macOS-M1-Preview-Documentation#8]
While working on this [PR](https://github.com/facebook/react-native/pull/36375/files), we figured out that `rbenv` is already installed. However, every time I try to send a command to Ruby, even just `ruby -v`, I get the following error:

```
/Users/distiller/.rbenv/shims/bundle: line 21: /usr/local/bin/rbenv: No such file or directory
``` 

This happens also when SSH-ing into the machine.

I couldn't find a work around for this.

**Comment by alexazl** [comment]
@cipolleschi Since we are no longer in preview, this repo will be archived. Please open a support ticket to investigate this issue further. Thank you!
